### ISSUE TITLE
License information is missing

### ISSUE THREAD

**Issue by skynyrds** [c-3po-org/plural-forms#12]
Hello, 
Could you please add an information about the package license and a copyright notice? The only mention of the license is in package.json file.
Thanks in advance!

**Comment by AlexMost** [comment]
Hi @skynyrds! Thanks for the issue, will fix that.

**Comment by skynyrds** [comment]
Ok, thanks! Could you please confirm that a package now has MIT license?

**Comment by AlexMost** [comment]
Yes, finally added it to the repo) - https://github.com/ttag-org/plural-forms/blob/master/LICENSE
